# Lista de países y sus IDs ISO 3166-1 alfa-3 (Algunos modificados)
countries = {
    "Afghanistan": "afg",
    "Albania": "alb",
    "Algeria": "alg",
    "Andorra": "and",
    "Angola": "ang",
    "Argentina": "arg",
    "Armenia": "arm",
    "Australia": "aus",
    "Austria": "aut",
    "Azerbaijan": "aze",
    "Bahrain": "bhr",
    "Bangladesh": "bgd",
    "Belgium": "bel",
    "Belize": "blz",
    "Benin": "ben",
    "Bolivia": "bol",
    "Bosnia and Herzegovina": "bih",
    "Botswana": "bot",
    "Brazil": "bra",
    "Brunei": "brn",
    "Bulgaria": "bul",
    "Burkina Faso": "bfa",
    "Burundi": "bdi",
    "Cabo Verde": "cpv",
    "Cambodia": "khm",
    "Cameroon": "cmr",
    "Canada": "can",
    "Chad": "cha",
    "Chile": "chi",
    "China": "chn",
    "Colombia": "col",
    "Comoros": "com",
    "Congo, Democratic Republic of the": "con",
    "Croatia": "cro",
    "Cuba": "cub",
    "Cyprus": "cyp",
    "Czech Republic": "cze",
    "Denmark": "den",
    "Djibouti": "dji",
    "Dominica": "dom",
    "Dominican Republic": "dom",
    "Ecuador": "ecu",
    "Egypt": "egy",
    "El Salvador": "els",
    "Estonia": "est",
    "Ethiopia": "eth",
    "Finland": "fin",
    "France": "fra",
    "Gabon": "gab",
    "Gambia": "gam",
    "Georgia": "geo",
    "Germany": "ger",
    "Ghana": "gha",
    "Greece": "gre",
    "Guatemala": "gua",
    "Guinea-Bissau": "gnb",
    "Guyana": "guy",
    "Haiti": "hai",
    "Honduras": "hon",
    "Hungary": "hun",
    "Iceland": "isl",
    "India": "ind",
    "Indonesia": "idn",
    "Iran": "irn",
    "Iraq": "irq",
    "Ireland": "irl",
    "Israel": "isr",
    "Italy": "ita",
    "Ivory Coast": "civ",
    "Jamaica": "jam",
    "Japan": "jpn",
    "Jordan": "jor",
    "Kazakhstan": "kaz",
    "Kenya": "ken",
    "Korea, South": "kor",
    "Kuwait": "kwt",
    "Kyrgyzstan": "kgz",
    "Laos": "lao",
    "Latvia": "lva",
    "Liberia": "lib",
    "Liechtenstein": "lie",
    "Lithuania": "ltu",
    "Luxembourg": "lux",
    "Madagascar": "mdg",
    "Malawi": "mwi",
    "Malaysia": "mys",
    "Maldives": "mdv",
    "Mali": "mli",
    "Malta": "mlt",
    "Mauritania": "mrt",
    "Mexico": "mex",
    "Mongolia": "mng",
    "Montenegro": "mnt",
    "Mozambique": "moz",
    "Myanmar": "mmr",
    "Namibia": "nam",
    "Netherlands": "ned",
    "New Zealand": "nwz",
    "Nicaragua": "nic",
    "Nigeria": "nga",
    "Norway": "nor",
    "Oman": "omn",
    "Palestine": "pse",
    "Panama": "pan",
    "Papua New Guinea": "png",
    "Paraguay": "par",
    "Peru": "per",
    "Philippines": "phl",
    "Poland": "pol",
    "Portugal": "por",
    "Qatar": "qat",
    "Romania": "rom",
    "Russia": "rus",
    "Rwanda": "rwa",
    "Saint Kitts and Nevis": "kna",
    "Sao Tome and Principe": "stp",
    "Saudi Arabia": "ksa",
    "Senegal": "sen",
    "Serbia": "scg",
    "Sierra Leone": "sle",
    "Singapore": "sgp",
    "Slovakia": "svk",
    "Slovenia": "slo",
    "South Africa": "rsa",
    "Spain": "esp",
    "Suriname": "sur",
    "Sweden": "swe",
    "Switzerland": "sui",
    "Syria": "syr",
    "Tanzania": "tza",
    "Thailand": "tha",
    "Trinidad and Tobago": "tri",
    "Tunisia": "tun",
    "Turkey": "tur",
    "Turkmenistan": "tkm",
    "Uganda": "uga",
    "Ukraine": "ukr",
    "United Arab Emirates": "uae",
    "United Kingdom": "UK",
    "United States": "usa",
    "Uruguay": "uru",
    "Uzbekistan": "uzb",
    "Vanuatu": "vut",
    "Venezuela": "ven",
    "Vietnam": "vnm",
    "Yemen": "yem",
    "Zambia": "zam",
    "Zimbabwe": "zim"
}
